server:
  port: 8888
  
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    tracing-enabled: true
    tools:
      schema-location-pattern: "**/*.graphqls"
      # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
      # specification and expectations of most clients, so use this option with caution
      introspection-enabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql

altair:
  mapping: /altair
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: Altair
  cdn:
    enabled: true
    version: 2.4.3

